# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='guest',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6),
        ),
    ]
