# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180223_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='data_arrival',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата приезда'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='data_departure',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата отъезда'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='patronomic',
            field=models.CharField(blank=True, max_length=64, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='sex',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], default=None, max_length=6, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='surname',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='table',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Table', verbose_name='Стол'),
        ),
    ]
